FROM ubuntu:16.04
LABEL name='kavita mishra'
LABEL email='kavita@gmail.com'
RUN apt-get update && apt-get install -y tree && apt-get install -y git
RUN touch /tmp/1.text
RUN touch /tmp/5.text
RUN touch /tmp/2.text
RUN touch /tmp/3.text
RUN touch /tmp/4.text
